spring:
  application:
    name: reviews

  metrics:
    servo:
      enabled: false

info:
  name: ${spring.application.name}
  version: ${version}

server:
  port: 8031

management:
  security:
    enabled: false

endpoints:
  sensitive: false
  shutdown:
    enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/