INSERT INTO review ( show_id, user_name, rating, review ) VALUES ( 'the-walking-dead', 'Tyron Lyle', 88, 'Proin vitae mi tellus. In cursus tortor vel molestie tempor. Nullam porta rutrum leo eu suscipit. Nunc ac odio tincidunt, interdum sem quis, pulvinar nibh. Maecenas a lobortis urna. Ut at sem at magna volutpat facilisis. Vestibulum cursus fringilla diam, ac pretium quam laoreet et. Vivamus quis blandit velit. Quisque.' );
INSERT INTO review ( show_id, user_name, rating, review ) VALUES ( 'the-walking-dead', 'Nat Ryker', 75, 'Integer mollis purus et malesuada porttitor. Nullam vehicula dui ac neque commodo tincidunt. Praesent tincidunt enim in eros iaculis, sit amet tristique lectus placerat. Aliquam sagittis urna sed rhoncus consectetur. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut ac quam mattis, scelerisque sapien non, lacinia.' );
INSERT INTO review ( show_id, user_name, rating, review ) VALUES ( 'the-walking-dead', 'Devyn Everard', 87, 'Donec ac sem sollicitudin metus maximus finibus et at massa. Quisque lobortis elementum ultricies. Aliquam faucibus eget arcu nec viverra. Curabitur tincidunt elit non metus rutrum scelerisque. Aenean ac imperdiet nibh. Sed dolor quam, rutrum vitae diam et, commodo tristique dolor. Maecenas facilisis, enim id sollicitudin ullamcorper, mi sapien viverra.' );
INSERT INTO review ( show_id, user_name, rating, review ) VALUES ( 'the-walking-dead', 'Zachery Lynton', 89, 'Donec iaculis mattis orci, sed feugiat orci scelerisque eu. Praesent nisi tellus, scelerisque in pharetra a, congue et urna. Nunc eget nunc auctor, porttitor justo eget, commodo magna. Nunc non sapien turpis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque gravida tincidunt tellus at vehicula.' );
INSERT INTO review ( show_id, user_name, rating, review ) VALUES ( 'the-walking-dead', 'Craig Ken', 74, 'Morbi vel mi rutrum, rutrum neque id, placerat velit. Integer non tellus vitae quam viverra posuere. Sed et massa libero. Nulla facilisi. Nullam ultrices eros id pellentesque condimentum. Quisque cursus lacus id leo accumsan tempus. Donec a ante justo. Curabitur accumsan placerat felis, et dignissim lectus. Ut ac velit vel.' );

INSERT INTO review ( show_id, user_name, rating, review ) VALUES ( 'breaking-bad', 'Elvin Dolph', 97, 'Proin vitae mi tellus. In cursus tortor vel molestie tempor. Nullam porta rutrum leo eu suscipit. Nunc ac odio tincidunt, interdum sem quis, pulvinar nibh. Maecenas a lobortis urna. Ut at sem at magna volutpat facilisis. Vestibulum cursus fringilla diam, ac pretium quam laoreet et. Vivamus quis blandit velit. Quisque.' );
INSERT INTO review ( show_id, user_name, rating, review ) VALUES ( 'breaking-bad', 'Lonnie Des', 92, 'Etiam maximus odio finibus est pulvinar accumsan. Nam nisi nunc, volutpat a vulputate quis, convallis non lectus. Fusce est justo, consectetur nec lorem eu, rutrum ornare magna. Fusce sollicitudin malesuada erat et efficitur. Sed mollis nec quam posuere egestas. Aliquam malesuada nec neque eget efficitur. Nunc tincidunt vel ex non.' );

INSERT INTO review ( show_id, user_name, rating, review ) VALUES ( 'game-of-thrones', 'Hildred Larry', 86, 'In viverra velit sit amet sem finibus vehicula. Phasellus vehicula nec nulla quis molestie. Nunc sed turpis imperdiet, accumsan risus a, commodo felis. Nunc congue massa ac laoreet laoreet. In hac habitasse platea dictumst. Vivamus at semper ipsum, pharetra convallis ante. Maecenas nunc felis, elementum in neque sed, lacinia efficitur.' );
INSERT INTO review ( show_id, user_name, rating, review ) VALUES ( 'game-of-thrones', 'Leith Cullen', 78, 'Suspendisse rutrum vulputate odio. Suspendisse urna ante, ultricies id semper facilisis, porta in libero. Phasellus congue libero neque, sit amet aliquam turpis maximus a. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis vel porta arcu. Vivamus sit amet diam nibh. Vestibulum libero diam, cursus sed.' );

INSERT INTO review ( show_id, user_name, rating, review ) VALUES ( 'orange-is-the-new-black', 'Kevin Cortney', 77, 'Praesent hendrerit vestibulum tortor, eget elementum nibh. Phasellus a ex at purus euismod lobortis. Fusce feugiat sollicitudin mauris et cursus. Proin venenatis, lacus eget aliquam pellentesque, enim ipsum suscipit felis, egestas ultricies turpis odio tincidunt ante. Phasellus tempor ornare nulla quis porttitor. Sed a mauris vel lorem rutrum consequat id.' );

INSERT INTO review ( show_id, user_name, rating, review ) VALUES ( 'house-of-cards', 'Montague Levi', 73, 'Donec vestibulum justo risus, sit amet ultrices purus volutpat non. Praesent facilisis justo at consequat euismod. Etiam dictum nibh sit amet ex malesuada finibus. Curabitur id pellentesque enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum id porttitor arcu. Nunc erat mauris, volutpat eu.' );
INSERT INTO review ( show_id, user_name, rating, review ) VALUES ( 'house-of-cards', 'Jordan Keaton', 79, 'Vestibulum vel iaculis mauris. Nullam venenatis luctus turpis quis eleifend. Ut at auctor lectus, et molestie nunc. Integer enim elit, suscipit nec augue id, facilisis eleifend magna. Cras ac consectetur ligula. Phasellus pharetra posuere enim ac suscipit. Vestibulum luctus venenatis odio, ut euismod turpis facilisis et. Suspendisse erat nunc, hendrerit.' );