spring:
  application:
    name: shows

  metrics:
    servo:
      enabled: false

  data:
    mongodb:
      port: 27017

info:
  name: ${spring.application.name}
  version: ${version}

server:
  port: 8011

management:
  security:
    enabled: false

endpoints:
  sensitive: false
  shutdown:
    enabled: true