spring:
  application:
    name: shows

  metrics:
    servo:
      enabled: false

  data:
    mongodb:
      port: 27017

  cloud:
    stream:
      bindings:
        actorChanges:
          group: shows

info:
  name: ${spring.application.name}
  version: ${version}

server:
  port: 8011

management:
  security:
    enabled: false

endpoints:
  sensitive: false
  shutdown:
    enabled: true

feign:
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 2000
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 500

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registryFetchIntervalSeconds: 2
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/