INSERT INTO show ( id, name, seasons, description) VALUES ('the-walking-dead', 'The walking dead', 6, 'The world we knew is gone. An epidemic of apocalyptic proportions has swept the globe causing the dead to rise and feed on the living. In a matter of months society has crumbled. In a world ruled by the dead, we are forced to finally start living. Based on a comic book series of the same name by Robert Kirkman, this AMC project focuses on the world after a zombie apocalypse. The series follows a police officer, Rick Grimes, who wakes up from a coma to find the world ravaged with zombies. Looking for his family, he and a group of survivors attempt to battle against the zombies in order to stay alive.');
INSERT INTO show_actors_id VALUES ('the-walking-dead', 'andrew-lincoln');
INSERT INTO show_actors_id VALUES ('the-walking-dead', 'jon-bernthal');
INSERT INTO show_actors_id VALUES ('the-walking-dead', 'sarah-wayne-callies');

INSERT INTO show ( id, name, seasons, description) VALUES ('breaking-bad', 'Breaking Bad', 5, 'Breaking Bad is an American crime drama television series created and produced by Vince Gilligan. The show originally aired on the AMC network for five seasons, from January 20, 2008, to September 29, 2013. It tells the story of Walter White (Bryan Cranston), a struggling high school chemistry teacher diagnosed with inoperable lung cancer, who, together with his former student Jesse Pinkman (Aaron Paul), turns to a life of crime, producing and selling crystallized methamphetamine to secure his family''s financial future before he dies. The title is from a Southern colloquialism meaning to "raise hell". Breaking Bad is set and was filmed in Albuquerque, New Mexico.');
INSERT INTO show_actors_id VALUES ('breaking-bad', 'bryan-cranston');

INSERT INTO show ( id, name, seasons, description) VALUES ('game-of-thrones', 'Game of Thrones', 5, 'Game of Thrones is an American fantasy drama television series created by showrunners David Benioff and D. B. Weiss. It is an adaptation of A Song of Ice and Fire, George R. R. Martin''s series of fantasy novels, the first of which is titled A Game of Thrones. It is filmed in a Belfast studio and on location elsewhere in Croatia, Iceland, Malta, Morocco, Northern Ireland, Spain, Scotland, and the United States, and premiered on HBO in the United States on April 17, 2011. The series completed airing its fifth season on June 14, 2015, and has been renewed for a sixth season.');
INSERT INTO show_actors_id VALUES ('game-of-thrones', 'sean-beann');

INSERT INTO show ( id, name, seasons, description) VALUES ('orange-is-the-new-black', 'Orange Is the New Black', 3, 'The series revolves around Piper Chapman (Taylor Schilling), a woman in her thirties living in New York City, who is sentenced to 15 months in Litchfield Penitentiary, a minimum-security women''s federal prison (operated by the "Federal Department of Corrections", a fictionalized version of the Federal Bureau of Prisons) in upstate New York. Piper has been convicted of transporting a suitcase full of drug money for her then girlfriend Alex Vause (Laura Prepon), an international drug smuggler. The offense had occurred 10 years prior to the start of the series, and in that time Piper had moved on to a quiet, law-abiding life among New York''s upper middle class, so her sudden and unexpected indictment seriously disrupts her relationships with her fiancé, family and friends.');
INSERT INTO show ( id, name, seasons, description) VALUES ('house-of-cards', 'House of Cards', 3, 'House of Cards is an American political drama television series developed and produced by Beau Willimon. It is an adaptation of the BBC''s mini-series of the same name and is based on the novel by Michael Dobbs. The entire first season, comprising thirteen episodes, premiered on February 1, 2013, on the streaming service Netflix. A second season of thirteen episodes premiered on February 14, 2014, while a third season premiered on February 27, 2015. House of Cards has been renewed for a fourth season, which will premiere in 2016. Willimon has stated that plans for the show''s future are decided after each season.');

